# vim:set ft=tmux:
%hidden MODULE_NAME="hostname"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "󱡶 "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_sapphire}"
set -ogq "@catppuccin_${MODULE_NAME}_text" " #(~/.tmux/plugins/hostname-tmux/hostname.tmux)"

source -F "~/.tmux/plugins/tmux/utils/status_module.conf"

